USE PIMS 
SELECT DISTINCT TABLE_SCHEMA, TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME
NOT  IN ( SELECT DISTINCT
TABLE_NAME
FROM INFORMATION_SCHEMA.VIEWS ) 
--AND 
--TABLE_NAME = 'bronze_datafeed'
-- 943 total
-- 429 views
-- 514 total not views

